function createDeck(seedString) {
  const deck = [];
  for (const suit of SUITS) {
    for (const rank of RANKS) {
      deck.push({
        id: getCardId(suit, rank.r),
        suit,
        rank: rank.r,
        value: rank.v,
      });
    }
  }
  seededShuffle(deck, seedString);
  return deck;
}

function createEmptyState() {
  return {
    deck: [],
    index: 0,
    current: null,
    cheats: [],
    pendingCheatOptions: [],
    pendingCheatAwardQueue: [],
    pendingPowerOptions: [],
    pendingPowerAwardQueue: [],
    powerChoiceRevealPending: false,
    pendingOpeningCardRevealed: false,
    pendingRunSeed: "",
    pendingRunDeck: [],
    pendingRunMode: "standard",
    pendingDailyDateKey: "",
    pendingDailyVariant: "normal",
    pendingDeckKey: loadSelectedDeck(),
    pendingLevelNumber: loadSelectedLevel(),
    powerChoiceLockedUntil: 0,
    message: "Press Start Run.",
    temporaryMessageText: "",
    temporaryMessageUntil: 0,
    playerLog: [],
    lastPlayerLogMessage: "",
    gameOver: true,
    openingPreview: false,
    gameOverMessageReady: false,
    gameOverMessageJustReleased: false,
    victoryMessageActive: false,
    victoryMessageJustReleased: false,
    experience: loadExperience(),
    displayExperience: null,
    experienceAwardedForRun: false,
    experienceBanking: null,
    experienceBankedCardIds: new Set(),
    experiencePreviewUntil: 0,
    experienceMilestonesAwarded: new Set(),
    pendingExperienceBonuses: [],
    unusedCheatExperienceAwarded: false,
    handCard: null,
    currentValueModifier: 0,
    currentNudgeUpUsed: 0,
    currentNudgeDownUsed: 0,
    currentNudgeValueModifier: 0,
    currentNudgeLogFlushed: false,
    nextCardValueModifier: 0,
    correctAnswers: 0,
    streak: 0,
    bestScore: loadBestScore(loadSelectedDeck(), loadSelectedLevel()),
    seenCardIds: new Set(),
    gridCardIds: new Set(),
    powers: [],
    selectedStartPowerId: null,
    selectedDeckKey: loadSelectedDeck(),
    currentDeckKey: loadSelectedDeck(),
    selectedLevelNumber: loadSelectedLevel(),
    currentLevelNumber: loadSelectedLevel(),
    runDebugLog: loadRunDebugLog(),
    metaProgression: loadMetaProgression(),
    cardStats: loadCardStats(),
    cardBackStatuses: loadCardBackStatuses(),
    temporaryCardBackRepairs: {},
    temporaryCardBackMarks: {},
    temporaryCardValues: {},
    cheatUnlocks: loadCheatUnlocks(),
    deckWins: loadDeckWins(),
    deckLevelClears: loadDeckLevelClears(),
    runMode: "standard",
    devMode: false,
    dailyDateKey: "",
    dailyVariant: "normal",
    dailyCheatOfferCount: 0,
    dailyPowerOfferCount: 0,
    dailyScoredBonusCheatPicks: 0,
    dailyScoredBonusPowerPicks: 0,
    justUnlockedCheatIds: [],
    cheatChoiceLockedUntil: 0,
    activeCheatAwardReason: "",
    activePowerAwardReason: "",
    pauseForCheat: false,
    cheatUsesOnCurrentCard: 0,
    lucky7Armed: false,
    fiveAliveArmed: false,
    fiveAliveNudgeLocked: false,
    marginForErrorArmed: false,
    hotOrColdArmed: false,
    stitchInTimeArmed: false,
    sellYourSoulArmed: false,
    higherHigherHigherRemaining: 0,
    psychoRemaining: 0,
    godSaveKingArmed: false,
    lucky13Armed: false,
    alwaysBetBlackArmed: false,
    redDeadRedemptionArmed: false,
    suitsYouSirArmed: false,
    suitsYouSirSuit: "",
    newSuitsRemaining: 0,
    newSuitsSeen: {},
    nineDartRemaining: 0,
    nineDartAutoCorrect: false,
    konamiPatternRemaining: [],
    konamiAutoCorrectRemaining: 0,
    findLadyArmed: false,
    saveScumArmed: false,
    saveScumPendingContinue: false,
    saveScumSnapshot: null,
    cryogenRemaining: 0,
    cryogenFrozenEnergy: 0,
    lockySevensActive: false,
    oddOneOutArmed: false,
    cursedShieldArmed: false,
    cursedShieldCharges: 0,
    nudgeNudgeArmed: false,
    nudgeNudgeStacks: 0,
    insuranceLives: 0,
    oneLifeLeftLives: 0,
    killerQueenLives: 0,
    suitedAndBootedArmed: false,
    suitedAndBootedSuit: "",
    blankSpaceActive: false,
    blankSpaceValue: null,
    forcedNextGuess: "",
    lockCurrentCardForForcedGuess: false,
    refundArmed: false,
    legendaryCheatOfferArmed: false,
    cheatACheaterRemaining: 0,
    allInRemaining: 0,
    allInNudgeUpStake: 0,
    allInNudgeDownStake: 0,
    wlStage: "",
    sixSevenArmed: false,
    sixSevenRewardChoicesRemaining: 0,
    equals11Armed: false,
    catch22Armed: false,
    blackjackArmed: false,
    diamondGeezerArmed: false,
    runSeed: loadLastRunSeed() || randomSeedString(),
    restartConfirmArmed: false,
    deckStatsTooltipOpen: false,
    victoryPromptShown: false,
    currentCardFeedback: "",
    pendingRevealAnimation: null,
    gameOverDisplayCards: null,
    cheatChoiceIntroToken: 0,
    powerChoiceIntroToken: 0,
    cheatChoicePreviewIndex: -1,
    cheatChoiceAnimating: null,
    recentlySeenCardId: "",
    nudgeUpCharges: 0,
    nudgeDownCharges: 0,
    bingoCornersAwarded: false,
    bingoLineAwardCount: 0,
    energy: 0,
    lastJokerMessage: "",
    rongActive: false,
  };
}

let state = createEmptyState();
